baseURL = 'https://pharmaka.med.schu.im/'
languageCode = 'de-de'
title = 'pharmaka.med.schu.im'
theme = "about-blank"
enableGitInfo = true

[params]
disableMenu = true

[markup.goldmark.renderer]
unsafe= true
